services:
  plexhub:
      image: ghcr.io/chakirhamzachahid/agregatorplextv:feature_serie
      container_name: plexhub-backend
      restart: unless-stopped
      network_mode: host
      environment:
        - PLEX_TOKEN=${PLEX_TOKEN}
        - TZ=Europe/Paris
      volumes:
        - /mnt/app-config/plexhub:/app/cache_assets
        - /mnt/app-config/plexhub/logs:/app/logs
      deploy:
        resources:
          limits:
            memory: 4G
            cpus: '2.0'
